version       = "0.1.0"
author        = "Nimclaw contributors"
description   = "Ultra-lightweight personal AI agent in Nim"
license       = "MIT"
srcDir        = "src"
bin           = @["nimclaw"]

requires "nim >= 2.0.0"
requires "jsony"
requires "cligen"
requires "regex"
requires "chronos"
requires "chronicles"
requires "websock"
requires "illwill >= 0.4.0"
requires "https://github.com/jaar23/tui_widget"
